#!/bin/bash
#SBATCH --partition=standard
#SBATCH --job-name=deconv_v1
#SBATCH -c 4
#SBATCH -o /mnt/cognosdata/EEG_MRI/derivatives/gridlog/deconv_v1-%j.out

echo This was run at: `date`

if [[ ! -v SLURM_CPUS_PER_TASK ]]; then
  echo Defaulting to 4 CPU threads 
  SLURM_CPUS_PER_TASK=4
fi

echo Job ID: $SLURM_JOB_ID
echo Job name: $SLURM_JOB_NAME
echo Submit host: $SLURM_SUBMIT_HOST
echo "Node(s) used": $SLURM_JOB_NODELIST

# Pass in the subject ID -- pull off any sub- bits to make sure clean
subjid=`echo $1 | sed s/sub-//`
ses=`echo $2 | sed s/Sess-//`

basedir=/mnt/cognosdata/EEG_MRI
outdir=$basedir/BIDS/derivatives/bold/GLM1/Sess$ses
indir=$basedir/BIDS/derivatives/fmriprep
mkdir -p $outdir
mkdir -p $outdir/sub-$subjid
mkdir -p $outdir/sub-$subjid/category

fulloutdir=$outdir/sub-$subjid/category
fullindir=$indir/sub-$subjid/ses-$ses/func
fullrawdir=$basedir/sub-$subjid/ses-$ses/func
1dfile=$basedir/BIDS/derivatives/fmriprep/GLM1dFiles/Categories1D

mkdir -p $fulloutdir

echo Starting 3dDeconvolve on $HOSTNAME with $NSLOTS slots at `date`
echo Input: $indir
echo  full: $fullindir
echo Output: $outdir
echo  full: $fulloutdir
echo Raw: $fullrawdir
echo Subj: $subjid


umask 0
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

SAFNI="singularity exec -B /mnt/cognosdata /mnt/mribin/singularity/afni_012821.sif"


if [ ! -e $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-all_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz ]; then
  echo Creating combined mask
  $SAFNI 3dcalc -prefix $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-all_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
  -a $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
  -b $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-02_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
  -c $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-03_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
  -d $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-04_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
  -e $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-05_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
  -f $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-06_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
  -g $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-07_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
  -expr "or(a,b,c,d,e,f,g)"
fi

$SAFNI 3dDeconvolve -input \
$fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz \
$fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-02_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz \
$fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-03_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz \
$fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-04_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz \
$fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-05_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz \
$fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-06_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz \
$fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-07_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz \
-polort 4 \
-mask $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-all_space-MNI152NLin6Asym_res-2_desc-brain_mask.nii.gz \
-num_stimts 14 \
-jobs $SLURM_CPUS_PER_TASK \
-local_times \
-stim_times 1 /mnt/cognosdata/EEG_MRI/BIDS/derivatives/fmriprep/GLM1dFiles/Categories1D/${subjid}_Category${categoryid}_Alltrials.1d 'SPMG3' -stim_label 1 Category \
-stim_times 2 /mnt/cognosdata/EEG_MRI/BIDS/derivatives/fmriprep/GLM1dFiles/Categories1D/${subjid}_Category${categoryid}_Alltrials.1d 'SPMG3' -stim_label 1 Category \
-stim_times 3 /mnt/cognosdata/EEG_MRI/BIDS/derivatives/fmriprep/GLM1dFiles/Categories1D/${subjid}_Category${categoryid}_Alltrials.1d 'SPMG3' -stim_label 1 Category \
-stim_times 4 /mnt/cognosdata/EEG_MRI/BIDS/derivatives/fmriprep/GLM1dFiles/Categories1D/${subjid}_Category${categoryid}_Alltrials.1d 'SPMG3' -stim_label 1 Category \
-stim_times 5 /mnt/cognosdata/EEG_MRI/BIDS/derivatives/fmriprep/GLM1dFiles/Categories1D/${subjid}_Responses.1d 'SPMG3' -stim_label 3 Responses \
-stim_file 6 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[9]' -stim_base 4 -stim_label 4 'WM' \
-stim_file 7 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[5]' -stim_base 5 -stim_label 5 'CSF' \
-stim_file 8 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[17]' -stim_base 6 -stim_label 6 'FD' \
-stim_file 9 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[18]' -stim_base 7 -stim_label 7 'dx' \
-stim_file 10 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[19]' -stim_base 8 -stim_label 8 'dy' \
-stim_file 11 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[20]' -stim_base 9 -stim_label 9 'dz' \
-stim_file 12 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[21]' -stim_base 10 -stim_label 10 'rotx' \
-stim_file 13 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[22]' -stim_base 11 -stim_label 11 'roty' \
-stim_file 14 $fullindir/sub-${subjid}_ses-${ses}_task-STORY_run-01_desc-confounds_timeseries_sarvia.tsv'[23]' -stim_base 12 -stim_label 12 'rotz' \
-gltsym 'SYM: +Category' -glt_label 1 Category \
-gltsym 'SYM: +Category' -glt_label 1 Category \
-gltsym 'SYM: +Category' -glt_label 1 Category \
-gltsym 'SYM: +Category' -glt_label 1 Category \
-bucket $fulloutdir/Category -fout -nocout \
-x1D_stop 

$SAFNI sh $fulloutdir/Category.REML_cmd -GOFORIT

# for sub in 302 303 305 306 307 309 310 311 312 313 314 315 316 317 318 319 320 322 323 324 325 326 327;do for object in {1..68}; do for ses in 1 2; do sbatch GLM1deconv_cs.sh $subjid $object $ses;done;done;done;
#-errts $fulloutdir/Deconv_v1_errts \
# -gltsym 'SYM: +OtherObjects' -glt_label 1 OtherObjects \
# -gltsym 'SYM: +Responses' -glt_label 2 Responses \
# -gltsym 'SYM: +Objects -OtherObjects' -glt_label 6 Objects_vs_OtherObjects \
# -gltsym 'SYM: +Objects -Responses' -glt_label 6 Objects_vs_Responses \
# -gltsym 'SYM: +OtherObjects -Responses' -glt_label 6 OtherObjects_vs_Responses \
# hello world

# for line 52, maybe add a 0 before the ? to make sure it picks up all runs if it doesnt run the first time
# -censor $fullindir/fmriprep_censor.1D \ we dont have a censor file, keep in case we need

# for sub in 703 704 705 706 708;do for categoryid in {1..4}; do for ses in 1 3; do sbatch GLM1deconv_csCategories.sh $subjid $categoryid $ses;done;done;done;
# for subjid in 703;do for categoryid in {1..4}; do for ses in 1 3; do sbatch GLM1deconv_csCategories.sh $subjid $categoryid $ses;done;done;done;
